# Generated by Django 4.1 on 2022-09-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_user_delete_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_seen_site',
        ),
    ]
