# Generated by Django 4.1 on 2022-08-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='time',
            field=models.IntegerField(),
        ),
    ]
