# Generated by Django 4.1 on 2022-08-03 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_image_u'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image_u',
            options={'managed': True, 'verbose_name': 'عکس پایینی', 'verbose_name_plural': 'ModelNames'},
        ),
    ]
