# Generated by Django 4.1 on 2022-08-03 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_image_u_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'verbose_name': ' دسته بندی ها', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'managed': True, 'verbose_name': ' ایمیل ها', 'verbose_name_plural': 'ایمیل ها'},
        ),
        migrations.AlterModelOptions(
            name='image_trend_3',
            options={'managed': True, 'verbose_name': ' سه عکس ترند', 'verbose_name_plural': 'سه عکس ترند'},
        ),
        migrations.AlterModelOptions(
            name='image_u',
            options={'managed': True, 'verbose_name': 'عکس پایینی', 'verbose_name_plural': 'عکس پایینی'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'managed': True, 'verbose_name': 'تخفیف ها ', 'verbose_name_plural': 'تخفیف ها'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='',
        ),
        migrations.AlterModelTable(
            name='email',
            table='',
        ),
        migrations.AlterModelTable(
            name='image_trend_3',
            table='',
        ),
        migrations.AlterModelTable(
            name='offer',
            table='',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('picture', models.ImageField(upload_to='ProductImage')),
                ('star', models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)])),
                ('caption', models.TextField()),
                ('detail', models.TextField()),
                ('buyers', models.IntegerField(default=0)),
                ('view', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('price_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.offer')),
            ],
            options={
                'verbose_name': 'محصولات',
                'verbose_name_plural': 'محصولات',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
