# Generated by Django 4.1 on 2022-08-04 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_alter_category_options_alter_email_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Tpost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='star',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.CreateModel(
            name='Userphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'شماره کاربر\u200d\u200d\u200d',
                'verbose_name_plural': '\u200dشماره کاربر',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
