# Generated by Django 4.1 on 2022-08-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_interest_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='sabad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pro', models.IntegerField()),
                ('id_user', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='interest',
            options={},
        ),
        migrations.AlterModelTable(
            name='interest',
            table=None,
        ),
    ]
