# Generated by Django 4.1 on 2022-08-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_sabad_alter_interest_options_alter_interest_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_trend_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='main/pic')),
                ('image2', models.ImageField(upload_to='main/pic')),
            ],
            options={
                'verbose_name': ' سه عکس ترند',
                'verbose_name_plural': 'سه عکس ترند',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='image_trend_3',
        ),
    ]
