# Generated by Django 4.1 on 2022-08-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_image_trend_2_delete_image_trend_3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image_trend_2',
            options={'managed': True, 'verbose_name': ' دو عکس ترند', 'verbose_name_plural': 'دو عکس ترند'},
        ),
        migrations.AlterField(
            model_name='image_trend_2',
            name='image1',
            field=models.ImageField(upload_to='main/pic/1'),
        ),
        migrations.AlterField(
            model_name='image_trend_2',
            name='image2',
            field=models.ImageField(upload_to='main/pic/2'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='time',
            field=models.DateField(),
        ),
    ]
