# Generated by Django 4.1 on 2022-08-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_image_trend_2_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
