# Generated by Django 4.1 on 2022-08-05 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_email_options_product_picture2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_offer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.offer'),
        ),
    ]
