# Generated by Django 4.1 on 2022-08-05 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_product_name_alter_product_price_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.offer'),
        ),
    ]
