# Generated by Django 4.1 on 2022-08-10 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_product_price_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='names',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='main.product'),
            preserve_default=False,
        ),
    ]
