# Generated by Django 4.1 on 2022-08-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_category_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vip',
            field=models.CharField(choices=[('yes', 'no')], default='خیر', max_length=20, verbose_name='محصول ویژه'),
        ),
    ]
