# Generated by Django 4.1 on 2022-08-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_product_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vip',
            field=models.CharField(choices=[('no', 'خیر'), ('yes', 'بله')], default='no', max_length=20, verbose_name='محصول ویژه'),
        ),
    ]
