# Generated by Django 4.1 on 2022-08-12 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_brand'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='email',
            unique_together={('Email',)},
        ),
    ]
