# Generated by Django 4.1 on 2022-08-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_email_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='email',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='email',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
