# Generated by Django 4.1 on 2022-08-13 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_image_u_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_u',
            name='category',
        ),
    ]
