# Generated by Django 4.1 on 2022-08-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_image_u_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_u',
            name='image',
            field=models.ImageField(upload_to='main/u', verbose_name='عکس'),
        ),
    ]
