# Generated by Django 4.1 on 2022-08-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_product_end_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='end_price',
        ),
    ]
