# Generated by Django 4.1 on 2022-08-14 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_product_end_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'verbose_name': 'علاقمندی ها', 'verbose_name_plural': 'علاقمندی ها'},
        ),
        migrations.AlterModelOptions(
            name='sabad',
            options={'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبد خرید'},
        ),
        migrations.AddField(
            model_name='image_trend_2',
            name='cat1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cat1', to='main.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image_trend_2',
            name='cat2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cat2', to='main.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='id_user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sabad',
            name='id_user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
