# Generated by Django 4.1 on 2022-08-14 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_interest_options_alter_sabad_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_trend_2',
            name='cat1',
        ),
        migrations.RemoveField(
            model_name='image_trend_2',
            name='cat2',
        ),
    ]
