# Generated by Django 4.1 on 2022-08-14 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_remove_image_trend_2_cat1_remove_image_trend_2_cat2'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_trend_2',
            name='cat1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cat1', to='main.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image_trend_2',
            name='cat2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cat2', to='main.category'),
            preserve_default=False,
        ),
    ]
