# Generated by Django 4.1 on 2022-08-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_image_trend_2_cat1_image_trend_2_cat2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='star',
            field=models.CharField(choices=[('1', 1), ('22', 2), ('333', 3), ('4444', 4), ('55555', 5)], max_length=25, verbose_name='امتیاز به ستاره'),
        ),
    ]
