# Generated by Django 4.1 on 2022-08-15 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_sabad_t'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sabad',
            name='T',
        ),
    ]
