# Generated by Django 4.1 on 2022-08-17 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0041_sabad_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sabad',
            name='T',
            field=models.IntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('user_id', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('Product_id', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='commentID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.comment'),
            preserve_default=False,
        ),
    ]
