# Generated by Django 4.1 on 2022-08-17 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_product_commentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='commentID',
        ),
    ]
