# Generated by Django 4.1 on 2022-08-17 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_remove_product_commentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commentID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.comment'),
        ),
    ]
