# Generated by Django 4.1 on 2022-08-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_remove_product_commentid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
