# Generated by Django 4.1 on 2022-08-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabad',
            name='jam',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
