# Generated by Django 4.1 on 2022-08-19 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0049_sabad_jam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sabad',
            options={},
        ),
        migrations.RemoveField(
            model_name='sabad',
            name='jam',
        ),
        migrations.CreateModel(
            name='jamsabad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jam', models.IntegerField(blank=True, null=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبد خرید',
            },
        ),
    ]
