# Generated by Django 4.1 on 2022-08-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_alter_jamsabad_id_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jamsabad',
            name='id_user',
            field=models.IntegerField(),
        ),
    ]
