# Generated by Django 4.1 on 2022-09-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_alter_jamsabad_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabad',
            name='p',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
