# Generated by Django 4.1 on 2022-09-07 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_sabad_p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jamsabad',
            name='id_pro',
        ),
    ]
