# Generated by Django 4.1 on 2022-09-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_remove_jamsabad_id_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabad',
            name='p2',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
